import { ChatMistralAI } from "@langchain/mistralai"

const maxPromptCharacters = 6000
const maxDescriptionCharacters = 180
const maxTitleCharacters = 80
const maxGeneratedTags = 10
const maxRagContextCharacters = 10000
const maxRagChunkCharacters = 1200
const maxInstagramDescriptionCharacters = 220
const maxYouTubeDescriptionCharacters = 220
const maxYouTubeTranscriptPromptCharacters = 4500
const stopWords = new Set([
    "about",
    "after",
    "again",
    "also",
    "because",
    "being",
    "between",
    "could",
    "document",
    "from",
    "have",
    "image",
    "into",
    "just",
    "like",
    "more",
    "only",
    "other",
    "over",
    "that",
    "their",
    "there",
    "these",
    "this",
    "upload",
    "using",
    "with",
    "would",
])

let mistralModel = null

// Generates clean title, description, and tags from extracted upload text using LangChain + Mistral.
// Input: extracted text string and optional metadata such as file name, file type, and fallback values.
// Output: object containing `title`, `description`, and normalized `tags`.
export async function generateUploadMetadataFromText(text, context = {}) {
    const model = getMistralModel()
    const response = await model.invoke([
        [
            "system",
            "Create clean metadata for uploaded PDFs or images. Return ONLY a JSON object with keys title, description, and tags. Never repeat garbled OCR. If text is unreliable, use the file name and file type to create neutral, readable metadata. Title must never be a hashtag list, email address, phone number, username wall, or URL. Description must summarize the content instead of dumping contact details or raw OCR noise. Keep title under 80 characters, description under 180 characters, and tags focused and useful.",
        ],
        ["human", buildMetadataPromptText(text, context)],
    ])
    
    const parsedMetadata = parseMetadataObject(normalizeModelContent(response?.content))

    return {
        title: normalizeGeneratedText(parsedMetadata?.title, maxTitleCharacters),
        description: normalizeGeneratedText(parsedMetadata?.description, maxDescriptionCharacters),
        tags: normalizeTags(Array.isArray(parsedMetadata?.tags) ? parsedMetadata.tags : []),
    }
}

// Generates 5-10 relevant tags from extracted content using LangChain + Mistral.
// Input: extracted text string and optional metadata such as file name and file type.
// Output: normalized array of tags ready to store in MongoDB.
export async function generateTagsFromText(text, context = {}) {
    const fallbackTags = buildFallbackTags(text, context)
    const metadata = await generateUploadMetadataFromText(text, context)
    const parsedTags = metadata.tags

    if (!parsedTags.length) {
        return fallbackTags
    }

    return mergeTags(parsedTags, fallbackTags)
}

// Generates a grounded final answer for a user question using retrieved Pinecone chunks as context.
// Input: natural-language query plus an ordered list of retrieved chunk-like objects.
// Output: concise answer text generated by Mistral.
export async function generateGroundedAnswer({ query, sources = [] }) {
    const normalizedQuery = String(query || "").trim()

    if (!normalizedQuery) {
        throw new Error("Query is required to generate a grounded answer")
    }

    const normalizedSources = normalizeRagSources(sources)

    if (!normalizedSources.length) {
        return "I could not find enough grounded context in your knowledge base to answer that question yet."
    }

    const model = getMistralModel()
    const response = await model.invoke([
        [
            "system",
            "You are a retrieval-augmented assistant for a private knowledge base. Answer only from the provided context. If the context is incomplete, say that clearly instead of guessing. Keep the answer crisp, helpful, and directly relevant to the user's question. Mention uncertainty when needed. Do not invent documents, facts, or citations.",
        ],
        ["human", buildGroundedAnswerPrompt(normalizedQuery, normalizedSources)],
    ])
    const answer = normalizeGeneratedText(
        normalizeModelContent(response?.content),
        maxRagContextCharacters,
    )

    return answer || "I found related context, but I could not turn it into a reliable answer."
}

// Generates a neutral Instagram description when metadata scraping returns no usable caption text.
// Input: Instagram URL plus any scraped title or preview image URL.
// Output: short description string that avoids hallucinating unseen details.
export async function generateInstagramDescriptionFallback({ url = "", title = "", imageUrl = "" }) {
    const model = getMistralModel()
    const response = await model.invoke([
        [
            "system",
            "Create a short, neutral description for an Instagram post saved into a private knowledge system. Use only the clues provided. If details are missing, do not invent what is visible in the image. Mention that it is an Instagram post and describe it cautiously.",
        ],
        [
            "human",
            [
                `Instagram URL: ${String(url || "").trim() || "unknown"}`,
                `Existing title: ${String(title || "").trim() || "unknown"}`,
                `Preview image URL: ${String(imageUrl || "").trim() || "unknown"}`,
                "Write one sentence under 220 characters.",
            ].join("\n"),
        ],
    ])

    return normalizeGeneratedText(
        normalizeModelContent(response?.content),
        maxInstagramDescriptionCharacters,
    )
}

// Generates a short English YouTube description from transcript or metadata.
// Input: YouTube URL plus the best-known title, channel name, and optional transcript text.
// Output: concise English description string safe to show on cards and use as a semantic summary.
export async function generateYouTubeEnglishDescription({
    url = "",
    title = "",
    channelName = "",
    transcriptText = "",
}) {
    const model = getMistralModel()
    const normalizedTranscript = String(transcriptText || "")
        .replace(/\s+/g, " ")
        .trim()
        .slice(0, maxYouTubeTranscriptPromptCharacters)
    const response = await model.invoke([
        [
            "system",
            "Create a short, neutral English description for a YouTube video saved into a private knowledge system. Use the transcript when available, otherwise use only the title, channel name, and URL clues provided. Do not invent unseen details or claims about the video. The output must be English only, one sentence, and under 220 characters.",
        ],
        [
            "human",
            [
                `YouTube URL: ${String(url || "").trim() || "unknown"}`,
                `Title: ${String(title || "").trim() || "unknown"}`,
                `Channel: ${String(channelName || "").trim() || "unknown"}`,
                `Transcript excerpt: ${normalizedTranscript || "Transcript unavailable"}`,
                "Write one sentence only in English.",
            ].join("\n"),
        ],
    ])

    return normalizeGeneratedText(
        normalizeModelContent(response?.content),
        maxYouTubeDescriptionCharacters,
    )
}

// Lazily creates the Mistral chat model so missing AI credentials do not break unrelated routes.
// Input: none.
// Output: configured ChatMistralAI instance.
export function getMistralModel() {
    if (mistralModel) {
        return mistralModel
    }

    const apiKey = String(process.env.MISTRAL_API_KEY || "").trim()

    if (!apiKey) {
        throw new Error("MISTRAL_API_KEY is not configured")
    }

    mistralModel = new ChatMistralAI({
        apiKey,
        model: process.env.MISTRAL_MODEL || "mistral-small-latest",
        temperature: 0,
        maxRetries: 2,
    })

    return mistralModel
}

// Builds a compact metadata prompt so the AI sees the file context, fallback hints, and the cleanest extracted text.
// Input: extracted text string and metadata object.
// Output: prompt string to send to the chat model.
function buildMetadataPromptText(text, context) {
    const normalizedText = String(text || "").trim()
    const clippedText = normalizedText.slice(0, maxPromptCharacters) || "No readable text was extracted from the file."

    return [
        `File name: ${context?.fileName || "unknown"}`,
        `File type: ${context?.fileType || "document"}`,
        `Text readable: ${context?.textReadable ? "yes" : "no"}`,
        `Fallback title: ${context?.fallbackTitle || "Uploaded File"}`,
        `Fallback description: ${context?.fallbackDescription || "Uploaded file saved to Second Brain."}`,
        "Extracted content:",
        clippedText,
    ].join("\n\n")
}

// Builds the final RAG prompt by packaging the user's question with clipped source chunks.
// Input: normalized query string and normalized retrieval source list.
// Output: prompt string ready for Mistral.
function buildGroundedAnswerPrompt(query, sources) {
    const contextBlocks = []
    let usedCharacters = 0

    for (const source of sources) {
        const block = [
            `Title: ${source.title}`,
            `Type: ${source.type}`,
            source.url ? `URL: ${source.url}` : "",
            `Context: ${source.text}`,
        ]
            .filter(Boolean)
            .join("\n")
        const nextLength = usedCharacters + block.length

        if (contextBlocks.length && nextLength > maxRagContextCharacters) {
            break
        }

        contextBlocks.push(block)
        usedCharacters = nextLength
    }

    return [
        "Answer the question using only the context below.",
        "",
        `Question: ${query}`,
        "",
        "Context:",
        contextBlocks.join("\n\n---\n\n") || "No relevant context provided.",
    ].join("\n")
}

// Clips retrieved sources into a prompt-safe structure before they are sent to the chat model.
// Input: raw retrieval source list.
// Output: normalized source list containing title, type, url, and chunk text.
function normalizeRagSources(sources) {
    if (!Array.isArray(sources)) {
        return []
    }

    return sources
        .map(source => {
            const title = normalizeGeneratedText(source?.metadata?.title || source?.title, maxTitleCharacters)
            const type = normalizeGeneratedText(source?.metadata?.type || source?.type || "document", 40)
            const url = normalizeGeneratedText(source?.metadata?.url || source?.url, 600)
            const text = normalizeGeneratedText(
                source?.metadata?.text || source?.matchedChunkText || source?.text,
                maxRagChunkCharacters,
            )

            if (!title || !text) {
                return null
            }

            return {
                title,
                type,
                url,
                text,
            }
        })
        .filter(Boolean)
}

// Normalizes the model output into a plain string for JSON parsing.
// Input: LangChain response content which may be a string or content block array.
// Output: flattened text string.
function normalizeModelContent(content) {
    if (typeof content === "string") {
        return content
    }

    if (Array.isArray(content)) {
        return content
            .map(part => {
                if (typeof part === "string") {
                    return part
                }

                if (typeof part?.text === "string") {
                    return part.text
                }

                return ""
            })
            .join("\n")
    }

    return ""
}

// Parses the Mistral response into a raw array of candidate tags.
// Input: model response text that should contain a JSON array.
// Output: array of string tags or an empty array when parsing fails.
function parseTagArray(content) {
    const cleanContent = String(content || "")
        .replace(/```json/gi, "")
        .replace(/```/g, "")
        .trim()

    const directResult = safeParseArray(cleanContent)
    if (directResult.length) {
        return directResult
    }

    const bracketMatch = cleanContent.match(/\[[\s\S]*\]/)

    if (!bracketMatch) {
        return []
    }

    return safeParseArray(bracketMatch[0])
}

// Parses the Mistral response into a metadata object with title, description, and tags.
// Input: model response text that should contain a JSON object.
// Output: plain object or an empty object when parsing fails.
function parseMetadataObject(content) {
    const cleanContent = String(content || "")
        .replace(/```json/gi, "")
        .replace(/```/g, "")
        .trim()

    const directResult = safeParseObject(cleanContent)
    if (Object.keys(directResult).length) {
        return directResult
    }

    const objectMatch = cleanContent.match(/\{[\s\S]*\}/)

    if (!objectMatch) {
        return {}
    }

    return safeParseObject(objectMatch[0])
}

// Safely parses JSON text and keeps only string array values.
// Input: JSON string that should represent an array.
// Output: array of strings or an empty array if parsing fails.
function safeParseArray(value) {
    try {
        const parsed = JSON.parse(value)

        if (!Array.isArray(parsed)) {
            return []
        }

        return parsed.filter(item => typeof item === "string")
    } catch {
        return []
    }
}

// Safely parses JSON text and keeps only plain-object values.
// Input: JSON string that should represent an object.
// Output: plain object or an empty object if parsing fails.
function safeParseObject(value) {
    try {
        const parsed = JSON.parse(value)

        if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") {
            return {}
        }

        return parsed
    } catch {
        return {}
    }
}

// Builds deterministic fallback tags from the text and file metadata.
// Input: extracted text string and metadata object.
// Output: normalized array of fallback tags.
function buildFallbackTags(text, context) {
    const candidates = [
        context?.fileType,
        "upload",
        ...extractKeywords(String(context?.fileName || "")),
        ...extractKeywords(text),
    ]

    return normalizeTags(candidates)
}

// Merges AI tags with fallback tags so saved content always keeps file-type context.
// Input: AI-generated tags and fallback tags.
// Output: deduplicated tag array capped at 10 entries.
function mergeTags(aiTags, fallbackTags) {
    return normalizeTags([
        ...aiTags,
        ...fallbackTags,
    ])
}

// Converts raw candidate tokens into clean searchable tags.
// Input: array of raw tag strings.
// Output: lowercase, deduplicated tags with a maximum length.
function normalizeTags(tags) {
    const normalizedTags = tags
        .map(sanitizeTag)
        .filter(Boolean)

    return [...new Set(normalizedTags)].slice(0, maxGeneratedTags)
}

// Extracts meaningful keywords from file names and text without relying on the AI.
// Input: free-form text value.
// Output: array of keyword candidates.
function extractKeywords(value) {
    return String(value || "")
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, " ")
        .split(/[\s-]+/)
        .filter(word => word.length > 2 && !stopWords.has(word))
        .slice(0, 8)
}

// Sanitizes a single tag so MongoDB stores consistent values.
// Input: raw tag string.
// Output: cleaned lowercase tag or an empty string.
function sanitizeTag(tag) {
    return String(tag || "")
        .toLowerCase()
        .trim()
        .replace(/^#+/, "")
        .replace(/[^a-z0-9-]+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-+|-+$/g, "")
}

// Normalizes short AI-generated text fields so upload metadata stays readable and compact.
// Input: raw AI-generated title or description string and a maximum character length.
// Output: cleaned string clipped to the requested size.
function normalizeGeneratedText(value, maxLength) {
    return String(value || "")
        .replace(/\s+/g, " ")
        .trim()
        .replace(/^["']+|["']+$/g, "")
        .slice(0, maxLength)
}
